---
title: "Anomalias_D1"
author: "Miguel Merelo Hernández"
date: "February 11, 2018"
output: pdf_document
---

```{r functions, include=FALSE}
source("../anomalias/!Outliers_A3_Funciones_a_cargar_en_cada_sesion2.R")
source("../anomalias/!Outliers_A2_Librerias_a_cargar_en_cada_sesion.R")
```

## Crear datos
Utilizamos LetterRecognition del paquete mlbench. Solo utilizamos las primeras 200 líneas ya que la visualización de 20000 entradas hace imposible analizar el problema.

```{r, message=F, warning=F}
library(mlbench)
data("LetterRecognition")
mis.datos.numericos<-LetterRecognition[1:200,-c(1)]
mis.datos.numericos.normalizados<-scale(mis.datos.numericos)
row.names(mis.datos.numericos.normalizados)<-row.names(mis.datos.numericos)
```

```{r}
alpha.value = 0.05
alpha.value.penalizado = 1 - ( 1 - alpha.value) ^ (1 / nrow(mis.datos.numericos))
set.seed(12) 
mvoutlier.plot<-uni.plot(mis.datos.numericos[1:10],
                         symb=FALSE,
                         alpha=alpha.value.penalizado)
```

```{r}
is.MCD.outlier<-mvoutlier.plot$outliers
numero.de.outliers.MCD<-sum(is.MCD.outlier)
numero.de.outliers.MCD
```

```{r}
corr.plot(mis.datos.numericos[,1], mis.datos.numericos[,3]) 
```

```{r}
MiBiplot(mis.datos.numericos)
```

# 1. DISTANCE BASED OUTLIERS (LOF)
```{r}
numero.de.vecinos.lof = 5
set.seed(12) 
lof.scores<-lofactor(mis.datos.numericos.normalizados,numero.de.vecinos.lof)
plot(lof.scores)
```

```{r}
numero.de.outliers = 4
indices.de.lof.outliers.ordenados<-order(lof.scores,decreasing=TRUE)
indices.de.lof.top.outliers<-indices.de.lof.outliers.ordenados[1:4]
indices.de.lof.top.outliers
```


```{r}
is.lof.outlier<-row.names(mis.datos.numericos) %in% indices.de.lof.top.outliers
MiBiPlot_Multivariate_Outliers(mis.datos.numericos,
                               is.lof.outlier,
                               "LETTERRECOGNITION")
```


```{r}
vector.claves.outliers.IQR.en.alguna.columna<-
  vector_claves_outliers_IQR_en_alguna_columna(mis.datos.numericos)
vector.claves.outliers.IQR.en.alguna.columna
```

```{r}
vector.es.outlier.IQR.en.alguna.columna<-vector_es_outlier_IQR_en_alguna_columna(mis.datos.numericos)
MiBiPlot_Multivariate_Outliers(mis.datos.numericos,vector.es.outlier.IQR.en.alguna.columna,"LETTERRECOGNITION")
indices.de.outliers.multivariantes.LOF.pero.no.1variantes<-setdiff(vector.claves.outliers.IQR.en.alguna.columna,indices.de.lof.top.outliers)
```

```{r}
data.frame.numeric<-LetterRecognition[sapply(LetterRecognition,is.numeric)]
head(data.frame.numeric)
```